nome = str(input('digite seu nome completo: ')).strip()
print('Seu nome em maisculo é: {}'.format(nome.upper()))
print('Seu nome em minusculo fica: {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print('Se primeiro nome tem {} letras'.format(nome.find(' ')))
print('Seu primeiro nome é {}'.format(nome.split()[0]))
