a = input(' Digite algo : ')
print('o tipo primitivo desse valor é ', type(a))
print('Só tem espaços ? {}'.format(a.isspace()))
print('è um numero ? {}' .format( a.isnumeric()))
print('é alfabetico ? {}' .format( a.isalpha()))
print('é alfanumérico ? {}' .format( a.isalnum()))
print(' está maiúsculo ? {}' .format( a.isupper()))
print('está minúsculo ? {}' .format( a.islower()))
print(' está capitalizada ? {}' .format( a.istitle()))
